const DB='OsRaDB', VER=1;
const DEFAULT={settings:{startDate:'',engagementDate:'',birthdayRania:'',osamaPhone:'',raniaPhone:'',whatsappUrl:'',libraryName:''},memories:[],events:[],dreams:[],verses:[],prayers:[],messages:[]};
let db,state=structuredClone(DEFAULT),libraryHandle=null,photos=new Map(),section='home',busy=false,installEvent=null,memoryDraft=null,lb={ids:[],i:0,url:null};
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const id=p=>p+'-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,8), today=()=>new Date().toISOString().slice(0,10);
const allPhotos=()=>[...photos.values()];
function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),2600)}
function dbOpen(){return new Promise((ok,no)=>{const r=indexedDB.open(DB,VER);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains('state'))d.createObjectStore('state',{keyPath:'key'});if(!d.objectStoreNames.contains('photos'))d.createObjectStore('photos',{keyPath:'id'});if(!d.objectStoreNames.contains('library'))d.createObjectStore('library',{keyPath:'key'})};r.onsuccess=()=>{db=r.result;ok()};r.onerror=()=>no(r.error)})}
const get=(s,k)=>new Promise((ok,no)=>{const r=db.transaction(s).objectStore(s).get(k);r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)});
const put=(s,v)=>new Promise((ok,no)=>{const r=db.transaction(s,'readwrite').objectStore(s).put(v);r.onsuccess=()=>ok();r.onerror=()=>no(r.error)});
const getAll=s=>new Promise((ok,no)=>{const r=db.transaction(s).objectStore(s).getAll();r.onsuccess=()=>ok(r.result||[]);r.onerror=()=>no(r.error)});
async function load(){const s=await get('state','main');if(s)state={...structuredClone(DEFAULT),...s.value,settings:{...DEFAULT.settings,...(s.value.settings||{})}};const l=await get('library','main');if(l?.handle){libraryHandle=l.handle;state.settings.libraryName=l.name||l.handle.name}photos=new Map((await getAll('photos')).map(x=>[x.id,x]))}
const save=()=>put('state',{key:'main',value:state});
function fmt(v){if(!v)return'بدون تاريخ';const d=new Date(v+'T00:00:00');return isNaN(d)?'بدون تاريخ':d.toLocaleDateString('ar-EG',{year:'numeric',month:'long',day:'numeric'})}
function duration(from){if(!from)return'لم نحدد التاريخ بعد';const a=new Date(from+'T00:00:00'),b=new Date(today()+'T00:00:00');if(a>b)return'لم يبدأ بعد';let y=b.getFullYear()-a.getFullYear(),m=b.getMonth()-a.getMonth(),d=b.getDate()-a.getDate();if(d<0){m--;d+=new Date(b.getFullYear(),b.getMonth(),0).getDate()}if(m<0){y--;m+=12}return [y&&`${y} سنة`,m&&`${m} شهر`,d&&`${d} يوم`].filter(Boolean).join(' و ')||'اليوم'}
function annual(v){if(!v)return null;const [y,m,d]=v.split('-').map(Number),n=new Date(),t=new Date(n.getFullYear(),m-1,d),z=new Date(n.getFullYear(),n.getMonth(),n.getDate());if(t<z)t.setFullYear(t.getFullYear()+1);return {date:t,days:Math.ceil((t-z)/86400000)}}
function dayLabel(n){return n===0?'اليوم ❤️':n===1?'غدًا':`بعد ${n} يومًا`}
function seed(){return [...today().replaceAll('-','')].reduce((a,c)=>a+c.charCodeAt(0),0)}
function setNav(){document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.section===section))}
function pageHome(){const p=allPhotos().sort((a,b)=>(a.addedAt||0)-(b.addedAt||0));const daily=p.length?p[seed()%p.length]:null;const same=state.memories.filter(m=>m.date&&m.date.slice(5)===today().slice(5));const up=[['بداية قصتنا',annual(state.settings.startDate),'♥'],['الخطوبة',annual(state.settings.engagementDate),'💍'],['عيد ميلاد رانيا',annual(state.settings.birthdayRania),'🎂']].filter(x=>x[1]).sort((a,b)=>a[1].date-b[1].date);return `<div class="inner"><div class="dedication"><div class="our">Our Story</div><div class="names">رانيا ♥ أسامة</div><div class="tag">قصتنا وصداقتنا</div><div class="line"></div><div class="small">من أول لحظة... إلى كل لحظة بعدها. ❤️</div><div class="feature card" style="width:min(640px,100%);margin-top:18px"><div class="memory-body"><b>📸 صورة اليوم</b></div>${daily?`<button class="memory-cover" data-action="photo" data-id="${daily.id}"><img data-thumb="${daily.id}" alt=""></button>`:`<div class="memory-cover"><span style="font:50px Georgia;color:var(--rose)">♥</span></div>`}<div class="memory-body"><b>${daily?esc(daily.name):'اربط مكتبة الصور للبدء'}</b></div></div></div><div class="stats"><div class="stat"><b>${state.memories.length}</b><small>ذكرى</small></div><div class="stat"><b>${photos.size}</b><small>صورة مفهرسة</small></div><div class="stat"><b>${state.dreams.length}</b><small>حلم</small></div><div class="stat"><b>${state.verses.length}</b><small>آية</small></div></div><div class="actions"><button class="btn primary" data-action="go" data-section="memories">فتح ذكرياتنا</button><button class="btn" data-action="go" data-section="story">رحلتنا</button><button class="btn" data-action="go" data-section="messages">رسائلنا ⭐</button></div><div class="line"></div><div class="grid"><div class="card"><b>⏳ معًا منذ</b><p>${duration(state.settings.startDate)}</p></div><div class="card"><b>💍 منذ الخطوبة</b><p>${duration(state.settings.engagementDate)}</p></div><div class="card"><b>📅 القادم</b><p>${up[0]?up[0][2]+' '+up[0][0]+' — '+dayLabel(up[0][1].days):'أضف التواريخ من الإعدادات'}</p></div></div>${same.length?`<div class="line"></div><h3>في مثل هذا اليوم ✨</h3><div class="cards">${same.map(m=>`<div class="card"><b>${esc(m.title)}</b><p>${fmt(m.date)}${m.place?' • '+esc(m.place):''}</p></div>`).join('')}</div>`:''}</div>`}
function pageMemories(){const q=(pageMemories.q||'').toLowerCase();const ms=state.memories.filter(m=>!q||[m.title,m.date,m.place,m.description,m.album].join(' ').toLowerCase().includes(q));return `<div class="inner"><div class="kicker">📸 ذكرياتنا</div><h1 class="title">ألبوماتنا</h1><p class="note">اختر مجلد <b>OsRa Photos</b>. كل مجلد فرعي يصبح ألبومًا، والصور الأصلية تظل خارج التطبيق.</p><div class="notice">${libraryHandle?'📁 مكتبة مرتبطة: '+esc(state.settings.libraryName||libraryHandle.name):'⚠️ لم يتم ربط مكتبة الصور بعد.'}</div><div class="actions" style="margin:12px 0"><button class="btn primary" data-action="folder">📁 ربط / استيراد</button><button class="btn" data-action="scan">↻ فحص جديد</button><button class="btn" data-action="addMemory">＋ ذكرى</button></div><div style="display:flex;gap:8px;margin-bottom:12px"><input id="searchMem" style="flex:1;padding:10px;border:1px solid var(--line);border-radius:12px;background:#fff8" placeholder="ابحث بالاسم أو المكان أو السنة" value="${esc(pageMemories.q||'')}"><button class="btn" data-action="search">بحث</button></div><div class="grid">${ms.length?ms.map(memoryCard).join(''):`<div class="empty" style="grid-column:1/-1">لا توجد نتائج.</div>`}</div></div>`}
function memoryCard(m){const p=(m.photoIds||[]).map(x=>photos.get(x)).find(Boolean);return `<article class="card memory-card"><div class="memory-cover">${p?`<img data-thumb="${p.id}" alt="">`:`<span style="font:48px Georgia;color:var(--rose)">♡</span>`}</div><div class="memory-body"><h3>${esc(m.title)}</h3><div class="meta">${m.date?fmt(m.date):'بدون تاريخ'}${m.place?' • '+esc(m.place):''}</div><p>${esc(m.description||'')}</p><div class="actions"><button class="btn small primary" data-action="memory" data-id="${m.id}">فتح</button><button class="btn small" data-action="editMemory" data-id="${m.id}">تعديل</button></div></div></article>`}
function pageMemory(m){return `<div class="inner"><div class="kicker">📖 ذكرى</div><h1 class="title">${esc(m.title)}</h1><p class="note">${m.date?fmt(m.date):'بدون تاريخ'}${m.place?' • '+esc(m.place):''}</p>${m.description?`<div class="quote">«${esc(m.description)}»</div>`:''}<div class="actions"><button class="btn" data-action="editMemory" data-id="${m.id}">✎ تعديل</button><button class="btn" data-action="backMemories">↩ ألبوماتنا</button></div><div class="gallery">${(m.photoIds||[]).map(x=>`<button class="thumb" data-action="photo" data-id="${x}"><img data-thumb="${x}" alt=""></button>`).join('')}</div>${m.photoIds?.length?`<p class="note">${m.photoIds.length} صورة</p>`:`<div class="empty">لا توجد صور في هذه الذكرى.</div>`}</div>`}
function pageStory(){const a=[...state.events.map(x=>({date:x.date,title:x.title,text:x.description,kind:'محطة'})),...state.memories.filter(x=>x.date).map(x=>({date:x.date,title:x.title,text:x.description,kind:'ذكرى'}))].sort((x,y)=>x.date.localeCompare(y.date));return `<div class="inner"><div class="kicker">◴ قصتنا</div><h1 class="title">رحلتنا</h1><p class="note">كل تاريخ وذكرى ومحطة يضيف صفحة جديدة.</p><button class="btn primary" data-action="event">＋ إضافة محطة</button><div class="timeline" style="margin-top:16px">${a.length?a.map(x=>`<div class="titem"><div class="tbox card"><div class="meta">${fmt(x.date)} • ${x.kind}</div><h3>${esc(x.title)}</h3><p>${esc(x.text||'')}</p></div></div>`).join(''):`<div class="empty">لم نضف محطات بعد.</div>`}</div></div>`}
function pageDreams(){const avg=state.dreams.length?Math.round(state.dreams.reduce((a,d)=>a+(+d.progress||0),0)/state.dreams.length):0;return `<div class="inner"><div class="kicker">✦ أحلامنا</div><h1 class="title">ما نحلم به</h1><p class="note">حلم + نسبة إنجاز + موعد، ثم يوم نكتب فيه «تحقق».</p><div class="card"><b>متوسط الإنجاز</b><p>${avg}%</p><div class="progress"><i style="width:${avg}%"></i></div></div><button class="btn primary" data-action="dream" style="margin:12px 0">＋ حلم</button><div class="cards">${state.dreams.length?state.dreams.map(d=>`<div class="card"><h3>${d.done?'✅':'🌱'} ${esc(d.title)}</h3><div class="meta">${d.targetDate?fmt(d.targetDate):'بدون موعد'}</div><p>${esc(d.note||'')}</p><div class="progress"><i style="width:${Math.min(100,Math.max(0,d.progress||0))}%"></i></div><p>${+d.progress||0}%</p><button class="btn small" data-action="editDream" data-id="${d.id}">تعديل</button></div>`).join(''):`<div class="empty">اكتبوا أول حلم.</div>`}</div></div>`}
function pageSpiritual(){const vs=state.verses||[],ps=state.prayers||[],daily=vs.length?vs[seed()%vs.length]:null;return `<div class="inner"><div class="kicker">☼ روحياتنا</div><h1 class="title">ما نحفظه في القلب</h1>${daily?`<div class="quote">«${esc(daily.text)}»<div class="meta">— ${esc(daily.ref||'')}</div></div>`:`<div class="empty">أضيفوا أول آية مفضلة لتظهر «آية اليوم» هنا.</div>`}<div class="actions" style="margin:14px 0"><button class="btn primary" data-action="verse">＋ آية</button><button class="btn" data-action="prayer">＋ صلاة / أمنية</button></div><h3>آياتنا</h3><div class="cards">${vs.length?vs.map(v=>`<div class="card"><div class="meta">${v.favorite?'⭐ ':''}${esc(v.ref||'')}</div><p>«${esc(v.text)}»</p><div class="actions"><button class="btn small" data-action="favVerse" data-id="${v.id}">${v.favorite?'إزالة ⭐':'تمييز ⭐'}</button><button class="btn small" data-action="delVerse" data-id="${v.id}">حذف</button></div></div>`).join(''):`<div class="empty">لا توجد آيات.</div>`}</div><div class="line"></div><h3>صلوات وأمنيات</h3><div class="cards">${ps.length?ps.map(p=>`<div class="card"><h3>${p.done?'✅':'🙏'} ${esc(p.title)}</h3><p>${esc(p.text||'')}</p><button class="btn small" data-action="togglePrayer" data-id="${p.id}">${p.done?'تراجع':'تحققت ♥'}</button></div>`).join(''):`<div class="empty">يمكنكم حفظ ما تصلّون أو تتمنون.</div>`}</div></div>`}
function pageMessages(){const ms=state.messages.filter(x=>x.starred),wa=state.settings.whatsappUrl||(state.settings.raniaPhone?`https://wa.me/${state.settings.raniaPhone.replace(/\D/g,'')}`:'');return `<div class="inner"><div class="kicker">✉ رسائلنا</div><h1 class="title">رسائل لا تُنسى ⭐</h1><p class="note">احفظ هنا ما يستحق البقاء؛ المحادثة الأصلية تبقى في واتساب.</p><div class="card"><b>📲 من واتساب إلى OsRa</b><p>يمكن مشاركة نص الرسالة إلى OsRa مباشرة بعد تثبيت التطبيق. وإذا لم يظهر OsRa في قائمة المشاركة، أضف الرسالة يدويًا.</p><button class="btn primary" data-action="message">＋ إضافة رسالة</button></div><div class="cards" style="margin-top:12px">${ms.length?ms.map(messageCard).join(''):`<div class="empty">لا توجد رسائل مميزة بعد.</div>`}</div>${wa?`<div class="line"></div><a class="btn primary" href="${esc(wa)}" target="_blank" rel="noopener">فتح محادثتنا في واتساب ↗</a>`:''}</div>`}
function messageCard(m){return `<div class="card"><div class="meta">⭐ ${fmt(m.date)} • ${esc(m.sender||'')}</div><p>«${esc(m.text)}»</p><div class="actions"><button class="btn small" data-action="toggleMessage" data-id="${m.id}">إزالة ⭐</button><button class="btn small" data-action="delMessage" data-id="${m.id}">حذف</button></div></div>`}
function pageSettings(){return `<div class="inner"><div class="kicker">⚙ المزيد</div><h1 class="title">إعدادات OsRa</h1><div class="cards"><div class="card"><h3>📁 مكتبة الصور</h3><p>${libraryHandle?'مرتبطة: '+esc(state.settings.libraryName||libraryHandle.name):'غير مرتبطة'}</p><div class="actions"><button class="btn primary" data-action="folder">اختيار / إعادة ربط</button><button class="btn" data-action="scan">↻ فحص</button><button class="btn" data-action="diag">تشخيص</button></div><p class="meta">${photos.size} صورة مفهرسة — الصور الأصلية لا تُرفع إلى GitHub.</p></div><div class="card"><h3>📅 التواريخ</h3><div class="formgrid">${field('setStart','بداية قصتنا',state.settings.startDate,'date')}${field('setEng','تاريخ الخطوبة',state.settings.engagementDate,'date')}${field('setBirth','عيد ميلاد رانيا',state.settings.birthdayRania,'date')}</div></div><div class="card"><h3>📱 التواصل</h3><div class="formgrid">${field('setOsama','رقم أسامة',state.settings.osamaPhone,'tel')}${field('setRania','رقم رانيا',state.settings.raniaPhone,'tel')}${field('setWA','رابط واتساب',state.settings.whatsappUrl,'url')}</div><button class="btn primary" data-action="settingsSave" style="margin-top:10px">حفظ</button></div><div class="card"><h3>💾 النسخة الاحتياطية</h3><p>تحفظ بيانات OsRa ومراجع الصور، وليست الصور الأصلية.</p><div class="actions"><button class="btn primary" data-action="backup">تصدير</button><button class="btn" data-action="restore">استرجاع</button></div></div></div></div>`}
function field(id,l,v,t){return `<div class="field"><label>${l}</label><input id="${id}" type="${t}" value="${esc(v||'')}"></div>`}
function pageHTML(s){return s==='home'?pageHome():s==='memories'?pageMemories():s==='story'?pageStory():s==='dreams'?pageDreams():s==='spiritual'?pageSpiritual():s==='messages'?pageMessages():pageSettings()}
function renderNoAnim(){ $('#currentPage').innerHTML=pageHTML(section); hydrate();setNav() }
function navigate(to,dir=1){if(to===section||busy)return;busy=true;const book=$('#book'),flip=$('#flipPage');flip.innerHTML=pageHTML(to);book.classList.remove('next','prev');void book.offsetWidth;book.classList.add(dir>0?'next':'prev');setTimeout(()=>{section=to;$('#currentPage').innerHTML=pageHTML(section);book.classList.remove('next','prev');busy=false;hydrate();setNav()},680)}
function hydrate(){document.querySelectorAll('[data-thumb]').forEach(el=>{const p=photos.get(el.dataset.thumb);if(!p?.thumbBlob)return;const u=URL.createObjectURL(p.thumbBlob);el.onload=()=>URL.revokeObjectURL(u);el.src=u})}
function go(to){const order=['home','memories','story','dreams','spiritual','messages','settings'];navigate(to,order.indexOf(to)>order.indexOf(section)?1:-1)}
async function permission(){if(!libraryHandle)return false;try{if(await libraryHandle.queryPermission({mode:'read'})==='granted')return true;return (await libraryHandle.requestPermission({mode:'read'}))==='granted'}catch{return false}}
function isImage(n){return /\.(jpe?g|png|webp|gif|avif|heic|heif)$/i.test(n)}
async function thumb(file){try{if(/heic|heif/i.test(file.name))return null;const b=await createImageBitmap(file),max=320,s=Math.min(1,max/Math.max(b.width,b.height)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(b.width*s));c.height=Math.max(1,Math.round(b.height*s));c.getContext('2d').drawImage(b,0,0,c.width,c.height);b.close?.();return await new Promise(r=>c.toBlob(r,'image/webp',.65))}catch{return null}}
async function chooseFolder(){if(!window.showDirectoryPicker){toast('استخدم Chrome حديثًا على Android ومن خلال HTTPS.');return}try{const h=await window.showDirectoryPicker({id:'OsRaPhotos',mode:'read'});libraryHandle=h;state.settings.libraryName=h.name;await put('library',{key:'main',handle:h,name:h.name});await save();await scan(h)}catch(e){if(e.name!=='AbortError')toast('تعذر ربط المجلد.')}}
async function scan(root=libraryHandle){if(!root)return chooseFolder();if(!await permission()){toast('إذن القراءة غير متاح. أعد ربط المكتبة.');return}toast('جارٍ فحص الصور…');let count=0,added=0;async function walk(dir,path=''){for await(const [name,e] of dir.entries()){const rel=path?path+'/'+name:name;if(e.kind==='directory'){await walk(e,rel);continue}if(!isImage(name))continue;count++;let f;try{f=await e.getFile()}catch{continue}let p=[...photos.values()].find(x=>x.relPath===rel);if(!p){p={id:id('ph'),relPath:rel,name,album:path?path.split('/')[0]:'صور',size:f.size,lastModified:f.lastModified,addedAt:Date.now(),thumbBlob:await thumb(f)};photos.set(p.id,p);await put('photos',p);ensureMemory(p.album,p.id);added++}else if(p.size!==f.size||p.lastModified!==f.lastModified){p.size=f.size;p.lastModified=f.lastModified;p.thumbBlob=await thumb(f);await put('photos',p);photos.set(p.id,p)}if(count%25===0){toast(`جارٍ الفحص… ${count} صورة`);await new Promise(r=>setTimeout(r,0))}}}try{await walk(root);await save();toast(`تم الفحص: ${count} صورة، ${added} جديدة.`);renderNoAnim()}catch{toast('حدث خطأ أثناء فحص المكتبة.')}}
function ensureMemory(album,pid){let m=state.memories.find(x=>x.album===album);if(!m){m={id:id('mem'),title:album,date:'',place:'',description:'',album,photoIds:[]};state.memories.push(m)}if(!m.photoIds.includes(pid))m.photoIds.push(pid)}
async function openPhoto(pid){const m=state.memories.find(x=>x.photoIds?.includes(pid));lb.ids=m?m.photoIds.slice():[pid];lb.i=Math.max(0,lb.ids.indexOf(pid));$('#lightbox').showModal();await showPhoto()}
async function resolve(root,rel){const ps=rel.split('/');let d=root;for(let i=0;i<ps.length-1;i++)d=await d.getDirectoryHandle(ps[i]);return d.getFileHandle(ps.at(-1))}
async function showPhoto(){const p=photos.get(lb.ids[lb.i]);if(!p)return;if(lb.url)URL.revokeObjectURL(lb.url);lb.url=null;$('#lbTitle').textContent=p.name;$('#lbStatus').textContent='جارٍ فتح الأصل…';$('#lbImage').removeAttribute('src');try{if(!(await permission()))throw 0;const fh=await resolve(libraryHandle,p.relPath),f=await fh.getFile();lb.url=URL.createObjectURL(f);$('#lbImage').src=lb.url;$('#lbStatus').textContent=''}catch{if(p.thumbBlob){lb.url=URL.createObjectURL(p.thumbBlob);$('#lbImage').src=lb.url;$('#lbStatus').textContent='الأصل غير متاح؛ المعروض نسخة مصغرة. أعد ربط المكتبة.'}else $('#lbStatus').textContent='الصورة غير متاحة.'}}
function closeLB(){if(lb.url)URL.revokeObjectURL(lb.url);lb.url=null;if($('#lightbox').open)$('#lightbox').close()}
function modal(html){$('#modalBody').innerHTML=html;$('#modal').showModal()}function closeModal(){memoryDraft=null;if($('#modal').open)$('#modal').close()}
function memoryForm(m){modal(`<h2>تفاصيل الذكرى</h2>${field('mTitle','اسم الذكرى',m.title,'text')}${field('mDate','التاريخ',m.date,'date')}${field('mPlace','المكان',m.place,'text')}<div class="field"><label>الوصف</label><textarea id="mDesc">${esc(m.description||'')}</textarea></div><div class="actions"><button class="btn primary" data-action="saveMemory" data-id="${m.id}">حفظ</button><button class="btn" data-action="closeModal">إلغاء</button></div>`)}
function editMemory(i){const m=state.memories.find(x=>x.id===i);if(m)memoryForm(m)}function addMemory(){const m={id:id('mem'),title:'',date:'',place:'',description:'',album:'',photoIds:[]};memoryDraft=m;memoryForm(m)}
function dreamForm(d){modal(`<h2>${d?'تعديل الحلم':'حلم جديد'}</h2>${field('dTitle','الحلم',d?.title||'','text')}${field('dDate','الموعد المستهدف',d?.targetDate||'','date')}${field('dProgress','نسبة الإنجاز',d?.progress??0,'number')}<div class="field"><label>التفاصيل</label><textarea id="dNote">${esc(d?.note||'')}</textarea></div><div class="actions"><button class="btn primary" data-action="saveDream" data-id="${d?.id||''}">حفظ</button><button class="btn" data-action="closeModal">إلغاء</button></div>`)}
function verseForm(){modal(`<h2>آية مفضلة</h2>${field('vRef','المرجع','','text')}<div class="field"><label>نص الآية</label><textarea id="vText"></textarea></div><button class="btn primary" data-action="saveVerse">حفظ</button>`)}
function prayerForm(){modal(`<h2>صلاة / أمنية</h2>${field('pTitle','العنوان','','text')}<div class="field"><label>التفاصيل</label><textarea id="pText"></textarea></div><button class="btn primary" data-action="savePrayer">حفظ</button>`)}
function msgForm(d={}){modal(`<h2>رسالة مميزة ⭐</h2>${field('msgDate','التاريخ',d.date||today(),'date')}${field('msgSender','من',d.sender||'رانيا','text')}<div class="field"><label>نص الرسالة</label><textarea id="msgText">${esc(d.text||'')}</textarea></div><button class="btn primary" data-action="saveMessage">حفظ</button>`)}
function eventForm(){modal(`<h2>محطة في قصتنا</h2>${field('eTitle','العنوان','','text')}${field('eDate','التاريخ',today(),'date')}<div class="field"><label>ماذا حدث؟</label><textarea id="eDesc"></textarea></div><button class="btn primary" data-action="saveEvent">حفظ</button>`)}
async function saveMemory(i){let m=state.memories.find(x=>x.id===i);if(!m&&memoryDraft?.id===i){m=memoryDraft;state.memories.unshift(m)}if(!m)return;m.title=$('#mTitle').value.trim()||'ذكرى بدون اسم';m.date=$('#mDate').value;m.place=$('#mPlace').value.trim();m.description=$('#mDesc').value.trim();memoryDraft=null;await save();closeModal();toast('تم حفظ الذكرى.');renderNoAnim()}
async function saveDream(i){let d=i?state.dreams.find(x=>x.id===i):null;if(!d){d={id:id('dream')};state.dreams.unshift(d)}d.title=$('#dTitle').value.trim()||'حلم';d.targetDate=$('#dDate').value;d.progress=Math.max(0,Math.min(100,Number($('#dProgress').value||0)));d.note=$('#dNote').value.trim();d.done=d.progress>=100;await save();closeModal();renderNoAnim()}
async function saveSettings(){for(const x of ['startDate','engagementDate','birthdayRania'])state.settings[x]=$('#set'+(x==='startDate'?'Start':x==='engagementDate'?'Eng':'Birth')).value;for(const [k,id2] of [['osamaPhone','setOsama'],['raniaPhone','setRania'],['whatsappUrl','setWA']])state.settings[k]=$('#'+id2).value.trim();await save();toast('تم حفظ الإعدادات.');renderNoAnim()}
async function saveVerse(){state.verses.unshift({id:id('v'),ref:$('#vRef').value.trim(),text:$('#vText').value.trim(),favorite:false});await save();closeModal();renderNoAnim()}
async function savePrayer(){state.prayers.unshift({id:id('p'),title:$('#pTitle').value.trim(),text:$('#pText').value.trim(),done:false});await save();closeModal();renderNoAnim()}
async function saveMessage(){state.messages.unshift({id:id('msg'),date:$('#msgDate').value,sender:$('#msgSender').value.trim(),text:$('#msgText').value.trim(),starred:true});await save();closeModal();renderNoAnim()}
async function saveEvent(){state.events.push({id:id('ev'),title:$('#eTitle').value.trim()||'محطة',date:$('#eDate').value,description:$('#eDesc').value.trim()});await save();closeModal();renderNoAnim()}
async function backup(){const payload={app:'OsRa',version:2,exportedAt:new Date().toISOString(),settings:state.settings,memories:state.memories,events:state.events,dreams:state.dreams,verses:state.verses,prayers:state.prayers,messages:state.messages,photoManifest:allPhotos().map(p=>({id:p.id,relPath:p.relPath,name:p.name,album:p.album,size:p.size,lastModified:p.lastModified,addedAt:p.addedAt}))};const a=document.createElement('a'),u=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));a.href=u;a.download='OsRa_Backup_'+today()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function restore(){const i=document.createElement('input');i.type='file';i.accept='.json,application/json';i.onchange=async()=>{try{const x=JSON.parse(await i.files[0].text());if(x.app!=='OsRa')throw 0;state={...structuredClone(DEFAULT),...x,settings:{...DEFAULT.settings,...x.settings}};await save();toast('تم الاسترجاع؛ أعد ربط مجلد الصور.');renderNoAnim()}catch{toast('ملف النسخة الاحتياطية غير صالح.')}};i.click()}
async function diagnostic(){const secure=!!isSecureContext,picker=!!window.showDirectoryPicker;let perm='لا توجد';if(libraryHandle)try{perm=await libraryHandle.queryPermission({mode:'read'})}catch{}const e=await navigator.storage?.estimate?.();modal(`<h2>تشخيص OsRa</h2><div class="cards"><div class="card">HTTPS/secure: <b>${secure?'نعم':'لا'}</b></div><div class="card">اختيار المجلد: <b>${picker?'متاح':'غير متاح'}</b></div><div class="card">الإذن: <b>${esc(perm)}</b></div><div class="card">الصور المفهرسة: <b>${photos.size}</b></div><div class="card">التخزين المستخدم: <b>${e?.usage?Math.round(e.usage/1024/1024)+' MB':'غير معروف'}</b></div></div>`)}

$('#nav').addEventListener('click',e=>{const b=e.target.closest('[data-section]');if(b)go(b.dataset.section)});
document.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action,i=b.dataset.id;try{if(a==='go')go(b.dataset.section);else if(a==='folder')await chooseFolder();else if(a==='scan')await scan();else if(a==='search'){pageMemories.q=$('#searchMem').value;renderNoAnim()}else if(a==='addMemory')addMemory();else if(a==='memory'){const m=state.memories.find(x=>x.id===i);if(m){$('#currentPage').innerHTML=pageMemory(m);hydrate()}}else if(a==='backMemories')renderNoAnim();else if(a==='editMemory')editMemory(i);else if(a==='saveMemory')await saveMemory(i);else if(a==='photo')await openPhoto(i);else if(a==='dream')dreamForm();else if(a==='editDream')dreamForm(state.dreams.find(x=>x.id===i));else if(a==='saveDream')await saveDream(i);else if(a==='verse')verseForm();else if(a==='saveVerse')await saveVerse();else if(a==='favVerse'){const x=state.verses.find(v=>v.id===i);if(x){x.favorite=!x.favorite;await save();renderNoAnim()}}else if(a==='delVerse'){state.verses=state.verses.filter(v=>v.id!==i);await save();renderNoAnim()}else if(a==='prayer')prayerForm();else if(a==='savePrayer')await savePrayer();else if(a==='togglePrayer'){const x=state.prayers.find(v=>v.id===i);if(x){x.done=!x.done;await save();renderNoAnim()}}else if(a==='message')msgForm();else if(a==='saveMessage')await saveMessage();else if(a==='toggleMessage'){const x=state.messages.find(v=>v.id===i);if(x){x.starred=!x.starred;await save();renderNoAnim()}}else if(a==='delMessage'){state.messages=state.messages.filter(v=>v.id!==i);await save();renderNoAnim()}else if(a==='event')eventForm();else if(a==='saveEvent')await saveEvent();else if(a==='settingsSave')await saveSettings();else if(a==='backup')await backup();else if(a==='restore')restore();else if(a==='diag')await diagnostic();else if(a==='closeModal')closeModal()}catch(err){console.error(err);toast('حدث خطأ. استخدم التشخيص إذا استمر.')}});
$('#modalClose').onclick=closeModal;$('#lbClose').onclick=closeLB;$('#lbPrev').onclick=async()=>{if(lb.i>0){lb.i--;await showPhoto()}};$('#lbNext').onclick=async()=>{if(lb.i<lb.ids.length-1){lb.i++;await showPhoto()}};
$('#book').addEventListener('touchstart',e=>{const t=e.changedTouches[0];$('#book').dataset.x=t.clientX;$('#book').dataset.y=t.clientY},{passive:true});$('#book').addEventListener('touchend',e=>{const t=e.changedTouches[0],x=+( $('#book').dataset.x||t.clientX),y=+( $('#book').dataset.y||t.clientY),dx=t.clientX-x,dy=t.clientY-y;if(Math.abs(dx)>65&&Math.abs(dx)>Math.abs(dy)*1.2){const order=['home','memories','story','dreams','spiritual','messages','settings'],j=order.indexOf(section)+(dx<0?1:-1);if(j>=0&&j<order.length)navigate(order[j],dx<0?1:-1)}},{passive:true});
$('#searchBtn').onclick=()=>modal(`<h2>بحث في OsRa</h2><div class="field"><label>كلمة البحث</label><input id="globalQ"></div><button class="btn primary" id="runGlobal">بحث</button><div id="globalOut" style="margin-top:12px"></div>`);
document.addEventListener('click',e=>{if(e.target.id==='runGlobal'){const q=($('#globalQ').value||'').toLowerCase(),o=[];state.memories.filter(x=>[x.title,x.date,x.place,x.description].join(' ').toLowerCase().includes(q)).forEach(x=>o.push('📸 '+x.title+' — '+fmt(x.date)));state.messages.filter(x=>[x.text,x.sender,x.date].join(' ').toLowerCase().includes(q)).forEach(x=>o.push('✉ '+x.sender+' — '+fmt(x.date)));state.dreams.filter(x=>[x.title,x.note,x.targetDate].join(' ').toLowerCase().includes(q)).forEach(x=>o.push('🌱 '+x.title));state.verses.filter(x=>[x.text,x.ref].join(' ').toLowerCase().includes(q)).forEach(x=>o.push('☼ '+x.ref));$('#globalOut').innerHTML=o.length?o.map(x=>`<div class="card">${esc(x)}</div>`).join(''):`<div class="empty">لا توجد نتائج.</div>`}});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installEvent=e;$('#installBtn').hidden=false});window.addEventListener('appinstalled',()=>{$('#installBtn').hidden=true;installEvent=null});$('#installBtn').onclick=async()=>{if(!installEvent){toast('التثبيت غير متاح على هذا المتصفح الآن.');return}const e=installEvent;installEvent=null;await e.prompt();try{const r=await e.userChoice;if(r.outcome!=='accepted')$('#installBtn').hidden=false;else $('#installBtn').hidden=true}catch{$('#installBtn').hidden=false}};
async function openShareTarget(){const q=new URLSearchParams(location.search),text=(q.get('text')||'').trim(),url=(q.get('url')||'').trim(),title=(q.get('title')||'').trim();if(!(text||url||title))return;const body=[text,url].filter(Boolean).join('\n');history.replaceState({},document.title,location.pathname+location.hash);msgForm({date:today(),sender:'واتساب',text:body||title})} (async()=>{try{await dbOpen();await load();renderNoAnim();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});await openShareTarget()}catch(e){console.error(e);toast('تعذر تشغيل OsRa.')}})();
